import { createVaultMemoryStore } from "./memoryStore";
import { resolveProjectMemoryScope } from "./projectMemoryScope";
import type { VaultMemoryEntry } from "./memoryTypes";
import type { VaultMemoryStatus } from "./memoryStatus";
import {
  CODE_SUMMARY_DEFAULT_EXCLUDED_DIRS,
  CODE_SUMMARY_SUPPORTED_EXTENSIONS,
  type CodeSummaryAnalysis,
  type CodeSummaryMemoryOptions,
  type CodeSummaryMemoryStatus,
  type CodeSummaryMemoryWriteResult,
  type CodeSummaryScanOptions,
} from "./codeSummaryTypes";
import { analyzeCodeSummaryFiles } from "./codeSummaryScanner";

function unique(values: string[]): string[] {
  return Array.from(
    new Set(
      values
        .map((value) => value.trim().toLowerCase())
        .filter(Boolean)
    )
  );
}

function mergeTags(...groups: readonly string[][]): string[] {
  return unique(groups.flat());
}

function isProtectedExistingStatus(status: VaultMemoryStatus): boolean {
  return status === "reviewed" || status === "approved" || status === "rejected" || status === "stale" || status === "superseded";
}

export async function previewCodeSummaryMemory(
  options: CodeSummaryScanOptions = {}
): Promise<CodeSummaryAnalysis[]> {
  return analyzeCodeSummaryFiles(options);
}

export async function createCodeSummaryMemoryCandidates(
  options: CodeSummaryMemoryOptions = {}
): Promise<CodeSummaryMemoryWriteResult> {
  const analyses = await analyzeCodeSummaryFiles(options);
  const store = createVaultMemoryStore();
  const scope = await resolveProjectMemoryScope({
    query: "code summary memory",
    projectId: options.projectId,
    version: options.version,
  });
  const projectId = scope.projectId ?? "chernobog";
  const version = scope.version;
  const entries: string[] = [];
  const warnings = [...scope.warnings];
  let created = 0;
  let updated = 0;
  let skipped = 0;
  let skippedApproved = 0;
  let skippedReviewed = 0;
  let skippedOtherStatuses = 0;

  for (const analysis of analyses) {
    const existing = await store.getEntry(analysis.id);
    if (existing && isProtectedExistingStatus(existing.status)) {
      skipped += 1;
      if (existing.status === "approved") {
        skippedApproved += 1;
      } else if (existing.status === "reviewed") {
        skippedReviewed += 1;
      } else {
        skippedOtherStatuses += 1;
      }
      continue;
    }

    const entry = await store.upsertEntry({
      id: analysis.id,
      title: analysis.title,
      body: analysis.body,
      source: "code",
      memoryType: "code-summary",
      status: "candidate",
      projectId,
      version,
      tags: mergeTags(analysis.tags, options.tags ?? []),
      confidence: analysis.confidence,
      sourceRef: {
        type: "code-file",
        path: analysis.file.relativePath,
      },
      reviewNotes: "Generated by V5.6.8 Source Code Summary Memory. Review before approval.",
    });

    entries.push(entry.id);
    if (existing) {
      updated += 1;
    } else {
      created += 1;
    }
  }

  if (analyses.length === 0) {
    warnings.push("No supported source files were found for code-summary memory.");
  }

  await store.appendAuditEvent({
    memoryEntryId: "code-summary-memory",
    action: "updated",
    actor: options.actor ?? "chernobog-code-summary-memory",
    note: `V5.6.8 generated ${created} new and ${updated} updated code-summary candidate entries. ${skipped} protected entries were skipped.`,
  });

  return {
    scannedFiles: analyses.length,
    created,
    updated,
    skipped,
    skippedApproved,
    skippedReviewed,
    skippedOtherStatuses,
    entries,
    warnings,
  };
}

export async function listCodeSummaryMemory(args: {
  projectId?: string;
  version?: string;
  statuses?: VaultMemoryStatus[];
  text?: string;
  limit?: number;
} = {}): Promise<VaultMemoryEntry[]> {
  const store = createVaultMemoryStore();
  return store.listEntries({
    memoryType: "code-summary",
    projectId: args.projectId,
    version: args.version,
    statuses: args.statuses,
    text: args.text,
    limit: args.limit ?? 50,
  });
}

export async function getCodeSummaryMemoryStatus(): Promise<CodeSummaryMemoryStatus> {
  const entries = await listCodeSummaryMemory({ limit: 10000 });
  const codeSummaryCounts: Record<string, number> = {};

  for (const entry of entries) {
    codeSummaryCounts[entry.status] = (codeSummaryCounts[entry.status] ?? 0) + 1;
  }

  return {
    supportedExtensions: CODE_SUMMARY_SUPPORTED_EXTENSIONS,
    defaultExcludedDirs: CODE_SUMMARY_DEFAULT_EXCLUDED_DIRS,
    codeSummaryCounts,
    totalCodeSummaryEntries: entries.length,
  };
}
